spring.application.name=apigateway

server.port=${PORT:8080}

# MongoDB
spring.data.mongodb.uri=mongodb+srv://malinibabu12345_db_user:test123@cluster0.pjzfxoe.mongodb.net/apigateway?retryWrites=true&w=majority

#JWT
gateway.auth.jwt-secret=${JWT_SECRET:mysupersecretkeymysupersecretkey12345}
gateway.auth.jwt-expiration-seconds=${JWT_EXPIRATION_SECONDS:3600}

#Rate Limit
gateway.rate-limit.max-tokens=${RATE_LIMIT_MAX_TOKENS:100}
gateway.rate-limit.refill-rate=${RATE_LIMIT_REFILL_RATE:10}

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
